source 'https://github.com/JY726/LJYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LJYAuthorKit_Example' do
  pod 'LJYAuthorKit', :path => '../'

  target 'LJYAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
